#! /bin/sh
set -e

# Vendors timzeone definition files into the `tz` folder
# See https://github.com/mde/timezone-js#setup for more information

rm -Rf tz
mkdir tz
curl ftp://ftp.iana.org/tz/tzdata-latest.tar.gz -o tz/tzdata-latest.tar.gz
tar -xvzf tz/tzdata-latest.tar.gz -C tz
rm tz/tzdata-latest.tar.gz
